<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Sobre</h2>
            <p>
                Este site foi uma forma encontrada pra treinar minhas habilidades de design de interfaces, então você não vai encontrar muita coisa aqui. Você pode estar se perguntando: "Porque não treinar frontend com algo útil?", simplesmente por falta de idéia :D. Tenho algo em comum com a maioria dos programadores backend: dificuldade com frontend, então melhor treinar né. Agora, fique com um pouco de lorem ipsum...
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum dolor sit amet consectetur adipiscing elit. Porta non pulvinar neque laoreet suspendisse. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. In fermentum et sollicitudin ac orci phasellus egestas. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Scelerisque eu ultrices vitae auctor eu augue ut. Accumsan lacus vel facilisis volutpat est velit egestas. Sed nisi lacus sed viverra tellus in hac habitasse. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Habitant morbi tristique senectus et netus. Ut sem viverra aliquet eget sit. Pretium fusce id velit ut tortor pretium viverra suspendisse. Senectus et netus et malesuada fames. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Nulla at volutpat diam ut venenatis tellus in metus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Pellentesque id nibh tortor id aliquet lectus proin. Augue ut lectus arcu bibendum at varius vel.
            </p>
            <p>
                Viverra tellus in hac habitasse platea. Rhoncus aenean vel elit scelerisque mauris. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Amet justo donec enim diam vulputate ut pharetra. Netus et malesuada fames ac. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Cursus in hac habitasse platea dictumst quisque sagittis. Netus et malesuada fames ac turpis egestas integer eget. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sit amet commodo nulla facilisi nullam vehicula. Eget sit amet tellus cras adipiscing enim eu turpis. Arcu felis bibendum ut tristique et egestas. A diam sollicitudin tempor id eu. Amet risus nullam eget felis eget nunc. Feugiat nibh sed pulvinar proin gravida hendrerit lectus.
            </p>
            <p> 
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum dolor sit amet consectetur adipiscing elit. Porta non pulvinar neque laoreet suspendisse. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. In fermentum et sollicitudin ac orci phasellus egestas. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Scelerisque eu ultrices vitae auctor eu augue ut. Accumsan lacus vel facilisis volutpat est velit egestas. Sed nisi lacus sed viverra tellus in hac habitasse. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Habitant morbi tristique senectus et netus. Ut sem viverra aliquet eget sit. Pretium fusce id velit ut tortor pretium viverra suspendisse. Senectus et netus et malesuada fames. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Nulla at volutpat diam ut venenatis tellus in metus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Pellentesque id nibh tortor id aliquet lectus proin. Augue ut lectus arcu bibendum at varius vel.
            </p>
            <p>
                Viverra tellus in hac habitasse platea. Rhoncus aenean vel elit scelerisque mauris. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Amet justo donec enim diam vulputate ut pharetra. Netus et malesuada fames ac. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Cursus in hac habitasse platea dictumst quisque sagittis. Netus et malesuada fames ac turpis egestas integer eget. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sit amet commodo nulla facilisi nullam vehicula. Eget sit amet tellus cras adipiscing enim eu turpis. Arcu felis bibendum ut tristique et egestas. A diam sollicitudin tempor id eu. Amet risus nullam eget felis eget nunc. Feugiat nibh sed pulvinar proin gravida hendrerit lectus.
            </p>
        </div>
    </div>
</div>